package fr.univ_lyon1.master_info.m2ti.tiw5.services.banque;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;

/**
 * This class was generated by Apache CXF 2.5.0
 * 2011-12-16T11:04:05.939+01:00
 * Generated source version: 2.5.0
 * 
 */
@WebService(targetNamespace = "http://master-info.univ-lyon1.fr/M2TI/TIW5/services/banque", name = "BanqueClient")
@XmlSeeAlso({ObjectFactory.class})
public interface BanqueClient {

    @Oneway
    @RequestWrapper(localName = "confirmOp", targetNamespace = "http://master-info.univ-lyon1.fr/M2TI/TIW5/services/banque", className = "fr.univ_lyon1.master_info.m2ti.tiw5.services.banque.ConfirmOp")
    @WebMethod(action = "http://master-info.univ-lyon1.fr/M2TI/TIW5/services/banque/confirmOp")
    public void confirmOp(
        @WebParam(name = "transaction-id", targetNamespace = "")
        java.lang.String transactionId,
        @WebParam(name = "valeur", targetNamespace = "")
        double valeur
    );
}
