package fr.univ_lyon1.master_info.m2ti.tiw5.services_fao;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2012-01-24T20:59:06.580+01:00
 * Generated source version: 2.4.2
 * 
 */
@WebService(targetNamespace = "http://master-info.univ-lyon1.fr/M2TI/TIW5/services_fao", name = "FAODataBase")
@XmlSeeAlso({ObjectFactory.class})
public interface FAODataBase {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "updateProduit", targetNamespace = "http://master-info.univ-lyon1.fr/M2TI/TIW5/services_fao", className = "fr.univ_lyon1.master_info.m2ti.tiw5.services_fao.UpdateProduit")
    @WebMethod
    @ResponseWrapper(localName = "updateProduitResponse", targetNamespace = "http://master-info.univ-lyon1.fr/M2TI/TIW5/services_fao", className = "fr.univ_lyon1.master_info.m2ti.tiw5.services_fao.UpdateProduitResponse")
    public java.lang.Boolean updateProduit(
        @WebParam(name = "pnum", targetNamespace = "")
        java.lang.String pnum,
        @WebParam(name = "pnom", targetNamespace = "")
        java.lang.String pnom,
        @WebParam(name = "composants", targetNamespace = "")
        java.util.List<java.lang.String> composants
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "deleteComposition", targetNamespace = "http://master-info.univ-lyon1.fr/M2TI/TIW5/services_fao", className = "fr.univ_lyon1.master_info.m2ti.tiw5.services_fao.DeleteComposition")
    @WebMethod
    @ResponseWrapper(localName = "deleteCompositionResponse", targetNamespace = "http://master-info.univ-lyon1.fr/M2TI/TIW5/services_fao", className = "fr.univ_lyon1.master_info.m2ti.tiw5.services_fao.DeleteCompositionResponse")
    public java.lang.Boolean deleteComposition(
        @WebParam(name = "pmajeur", targetNamespace = "")
        java.lang.String pmajeur,
        @WebParam(name = "pmineur", targetNamespace = "")
        java.lang.String pmineur
    );

    @WebResult(name = "produitList", targetNamespace = "")
    @RequestWrapper(localName = "getProduitList", targetNamespace = "http://master-info.univ-lyon1.fr/M2TI/TIW5/services_fao", className = "fr.univ_lyon1.master_info.m2ti.tiw5.services_fao.GetProduitList")
    @WebMethod
    @ResponseWrapper(localName = "getProduitListResponse", targetNamespace = "http://master-info.univ-lyon1.fr/M2TI/TIW5/services_fao", className = "fr.univ_lyon1.master_info.m2ti.tiw5.services_fao.GetProduitListResponse")
    public java.util.List<fr.univ_lyon1.master_info.m2ti.tiw5.services_fao.PnumPnom> getProduitList();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "addProduit", targetNamespace = "http://master-info.univ-lyon1.fr/M2TI/TIW5/services_fao", className = "fr.univ_lyon1.master_info.m2ti.tiw5.services_fao.AddProduit")
    @WebMethod
    @ResponseWrapper(localName = "addProduitResponse", targetNamespace = "http://master-info.univ-lyon1.fr/M2TI/TIW5/services_fao", className = "fr.univ_lyon1.master_info.m2ti.tiw5.services_fao.AddProduitResponse")
    public java.lang.Boolean addProduit(
        @WebParam(name = "pnum", targetNamespace = "")
        java.lang.String pnum,
        @WebParam(name = "pnom", targetNamespace = "")
        java.lang.String pnom,
        @WebParam(name = "composants", targetNamespace = "")
        java.util.List<java.lang.String> composants
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "deleteProduit", targetNamespace = "http://master-info.univ-lyon1.fr/M2TI/TIW5/services_fao", className = "fr.univ_lyon1.master_info.m2ti.tiw5.services_fao.DeleteProduit")
    @WebMethod
    @ResponseWrapper(localName = "deleteProduitResponse", targetNamespace = "http://master-info.univ-lyon1.fr/M2TI/TIW5/services_fao", className = "fr.univ_lyon1.master_info.m2ti.tiw5.services_fao.DeleteProduitResponse")
    public java.lang.Boolean deleteProduit(
        @WebParam(name = "pnum", targetNamespace = "")
        java.lang.String pnum
    );

    @WebResult(name = "compositionList", targetNamespace = "")
    @RequestWrapper(localName = "getCompositionList", targetNamespace = "http://master-info.univ-lyon1.fr/M2TI/TIW5/services_fao", className = "fr.univ_lyon1.master_info.m2ti.tiw5.services_fao.GetCompositionList")
    @WebMethod
    @ResponseWrapper(localName = "getCompositionListResponse", targetNamespace = "http://master-info.univ-lyon1.fr/M2TI/TIW5/services_fao", className = "fr.univ_lyon1.master_info.m2ti.tiw5.services_fao.GetCompositionListResponse")
    public java.util.List<fr.univ_lyon1.master_info.m2ti.tiw5.services_fao.PmajeurPmineur> getCompositionList();
}
