package fr.univ_lyon1.master_info.m2ti.tiw5.services;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2012-01-22T23:17:44.772+01:00
 * Generated source version: 2.4.2
 * 
 */
@WebService(targetNamespace = "http://master-info.univ-lyon1.fr/M2TI/TIW5/services", name = "CAODataBase")
@XmlSeeAlso({ObjectFactory.class})
public interface CAODataBase {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "addComposition", targetNamespace = "http://master-info.univ-lyon1.fr/M2TI/TIW5/services", className = "fr.univ_lyon1.master_info.m2ti.tiw5.services.AddComposition")
    @WebMethod
    @ResponseWrapper(localName = "addCompositionResponse", targetNamespace = "http://master-info.univ-lyon1.fr/M2TI/TIW5/services", className = "fr.univ_lyon1.master_info.m2ti.tiw5.services.AddCompositionResponse")
    public java.lang.Boolean addComposition(
        @WebParam(name = "pmajeur", targetNamespace = "")
        long pmajeur,
        @WebParam(name = "pmineur", targetNamespace = "")
        long pmineur
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "deleteProduit", targetNamespace = "http://master-info.univ-lyon1.fr/M2TI/TIW5/services", className = "fr.univ_lyon1.master_info.m2ti.tiw5.services.DeleteProduit")
    @WebMethod
    @ResponseWrapper(localName = "deleteProduitResponse", targetNamespace = "http://master-info.univ-lyon1.fr/M2TI/TIW5/services", className = "fr.univ_lyon1.master_info.m2ti.tiw5.services.DeleteProduitResponse")
    public java.lang.Boolean deleteProduit(
        @WebParam(name = "pnum", targetNamespace = "")
        long pnum
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "deleteComposition", targetNamespace = "http://master-info.univ-lyon1.fr/M2TI/TIW5/services", className = "fr.univ_lyon1.master_info.m2ti.tiw5.services.DeleteComposition")
    @WebMethod
    @ResponseWrapper(localName = "deleteCompositionResponse", targetNamespace = "http://master-info.univ-lyon1.fr/M2TI/TIW5/services", className = "fr.univ_lyon1.master_info.m2ti.tiw5.services.DeleteCompositionResponse")
    public java.lang.Boolean deleteComposition(
        @WebParam(name = "pmajeur", targetNamespace = "")
        long pmajeur,
        @WebParam(name = "pmineur", targetNamespace = "")
        long pmineur
    );

    @WebResult(name = "produitList", targetNamespace = "")
    @RequestWrapper(localName = "getProduitList", targetNamespace = "http://master-info.univ-lyon1.fr/M2TI/TIW5/services", className = "fr.univ_lyon1.master_info.m2ti.tiw5.services.GetProduitList")
    @WebMethod
    @ResponseWrapper(localName = "getProduitListResponse", targetNamespace = "http://master-info.univ-lyon1.fr/M2TI/TIW5/services", className = "fr.univ_lyon1.master_info.m2ti.tiw5.services.GetProduitListResponse")
    public java.util.List<fr.univ_lyon1.master_info.m2ti.tiw5.services.PnumPnom> getProduitList();

    @WebResult(name = "compositionList", targetNamespace = "")
    @RequestWrapper(localName = "getCompositionList", targetNamespace = "http://master-info.univ-lyon1.fr/M2TI/TIW5/services", className = "fr.univ_lyon1.master_info.m2ti.tiw5.services.GetCompositionList")
    @WebMethod
    @ResponseWrapper(localName = "getCompositionListResponse", targetNamespace = "http://master-info.univ-lyon1.fr/M2TI/TIW5/services", className = "fr.univ_lyon1.master_info.m2ti.tiw5.services.GetCompositionListResponse")
    public java.util.List<fr.univ_lyon1.master_info.m2ti.tiw5.services.PmajeurPmineur> getCompositionList();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "addProduit", targetNamespace = "http://master-info.univ-lyon1.fr/M2TI/TIW5/services", className = "fr.univ_lyon1.master_info.m2ti.tiw5.services.AddProduit")
    @WebMethod
    @ResponseWrapper(localName = "addProduitResponse", targetNamespace = "http://master-info.univ-lyon1.fr/M2TI/TIW5/services", className = "fr.univ_lyon1.master_info.m2ti.tiw5.services.AddProduitResponse")
    public java.lang.Boolean addProduit(
        @WebParam(name = "pnum", targetNamespace = "")
        long pnum,
        @WebParam(name = "pnom", targetNamespace = "")
        java.lang.String pnom
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "updateProduit", targetNamespace = "http://master-info.univ-lyon1.fr/M2TI/TIW5/services", className = "fr.univ_lyon1.master_info.m2ti.tiw5.services.UpdateProduit")
    @WebMethod
    @ResponseWrapper(localName = "updateProduitResponse", targetNamespace = "http://master-info.univ-lyon1.fr/M2TI/TIW5/services", className = "fr.univ_lyon1.master_info.m2ti.tiw5.services.UpdateProduitResponse")
    public java.lang.Boolean updateProduit(
        @WebParam(name = "pnum", targetNamespace = "")
        long pnum,
        @WebParam(name = "pnom", targetNamespace = "")
        java.lang.String pnom
    );
}
