
package fr.univ_lyon1.master_info.m2ti.tiw5.services_fao;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2012-01-13T08:44:03.123+01:00
 * Generated source version: 2.4.2
 * 
 */
public final class FAODataBase_FAODataBaseSOAP_Client {

    private static final QName SERVICE_NAME = new QName("http://master-info.univ-lyon1.fr/M2TI/TIW5/services_fao", "FAODataBase");

    private FAODataBase_FAODataBaseSOAP_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = FAODataBase_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        FAODataBase_Service ss = new FAODataBase_Service(wsdlURL, SERVICE_NAME);
        FAODataBase port = ss.getFAODataBaseSOAP();  
        
        {
        System.out.println("Invoking updateProduit...");
        java.lang.String _updateProduit_pnum = "";
        java.lang.String _updateProduit_pnom = "";
        java.util.List<java.lang.String> _updateProduit_composants = null;
        java.lang.Boolean _updateProduit__return = port.updateProduit(_updateProduit_pnum, _updateProduit_pnom, _updateProduit_composants);
        System.out.println("updateProduit.result=" + _updateProduit__return);


        }
        {
        System.out.println("Invoking deleteComposition...");
        java.lang.String _deleteComposition_pmajeur = "";
        java.lang.String _deleteComposition_pmineur = "";
        java.lang.Boolean _deleteComposition__return = port.deleteComposition(_deleteComposition_pmajeur, _deleteComposition_pmineur);
        System.out.println("deleteComposition.result=" + _deleteComposition__return);


        }
        {
        System.out.println("Invoking getProduitList...");
        java.util.List<fr.univ_lyon1.master_info.m2ti.tiw5.services_fao.PnumPnom> _getProduitList__return = port.getProduitList();
        System.out.println("getProduitList.result=" + _getProduitList__return);


        }
        {
        System.out.println("Invoking addProduit...");
        java.lang.String _addProduit_pnum = "";
        java.lang.String _addProduit_pnom = "";
        java.util.List<java.lang.String> _addProduit_composants = null;
        java.lang.Boolean _addProduit__return = port.addProduit(_addProduit_pnum, _addProduit_pnom, _addProduit_composants);
        System.out.println("addProduit.result=" + _addProduit__return);


        }
        {
        System.out.println("Invoking deleteProduit...");
        java.lang.String _deleteProduit_pnum = "";
        java.lang.Boolean _deleteProduit__return = port.deleteProduit(_deleteProduit_pnum);
        System.out.println("deleteProduit.result=" + _deleteProduit__return);


        }
        {
        System.out.println("Invoking getCompositionList...");
        java.util.List<fr.univ_lyon1.master_info.m2ti.tiw5.services_fao.PmajeurPmineur> _getCompositionList__return = port.getCompositionList();
        System.out.println("getCompositionList.result=" + _getCompositionList__return);


        }

        System.exit(0);
    }

}
