package fr.univ_lyon1.master_info.m2ti.tiw5.services_fao;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2012-01-13T08:44:03.253+01:00
 * Generated source version: 2.4.2
 * 
 */
@WebServiceClient(name = "FAODataBase", 
                  wsdlLocation = "file:/Users/padawanchichi/Documents/divers/Cours/TIW3/projet/client/src/main/resources/FAODataBaseService.wsdl",
                  targetNamespace = "http://master-info.univ-lyon1.fr/M2TI/TIW5/services_fao") 
public class FAODataBase_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://master-info.univ-lyon1.fr/M2TI/TIW5/services_fao", "FAODataBase");
    public final static QName FAODataBaseSOAP = new QName("http://master-info.univ-lyon1.fr/M2TI/TIW5/services_fao", "FAODataBaseSOAP");
    static {
        URL url = null;
        try {
            url = new URL("file:/Users/padawanchichi/Documents/divers/Cours/TIW3/projet/client/src/main/resources/FAODataBaseService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(FAODataBase_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/Users/padawanchichi/Documents/divers/Cours/TIW3/projet/client/src/main/resources/FAODataBaseService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public FAODataBase_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public FAODataBase_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FAODataBase_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns FAODataBase
     */
    @WebEndpoint(name = "FAODataBaseSOAP")
    public FAODataBase getFAODataBaseSOAP() {
        return super.getPort(FAODataBaseSOAP, FAODataBase.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FAODataBase
     */
    @WebEndpoint(name = "FAODataBaseSOAP")
    public FAODataBase getFAODataBaseSOAP(WebServiceFeature... features) {
        return super.getPort(FAODataBaseSOAP, FAODataBase.class, features);
    }

}
