package fr.univ_lyon1.master_info.m2ti.tiw5.services.banque;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.5.0
 * 2011-12-16T11:04:05.986+01:00
 * Generated source version: 2.5.0
 * 
 */
@WebServiceClient(name = "BanqueClient", 
                  wsdlLocation = "file:/C:/Users/Seb/eclipse-projects/svn/Multimif/projet/provided-services/src/main/resources/wsdl/BanqueClient.wsdl",
                  targetNamespace = "http://master-info.univ-lyon1.fr/M2TI/TIW5/services/banque") 
public class BanqueClient_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://master-info.univ-lyon1.fr/M2TI/TIW5/services/banque", "BanqueClient");
    public final static QName BanqueClientSOAP = new QName("http://master-info.univ-lyon1.fr/M2TI/TIW5/services/banque", "BanqueClientSOAP");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/Seb/eclipse-projects/svn/Multimif/projet/provided-services/src/main/resources/wsdl/BanqueClient.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(BanqueClient_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/Seb/eclipse-projects/svn/Multimif/projet/provided-services/src/main/resources/wsdl/BanqueClient.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public BanqueClient_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public BanqueClient_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BanqueClient_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns BanqueClient
     */
    @WebEndpoint(name = "BanqueClientSOAP")
    public BanqueClient getBanqueClientSOAP() {
        return super.getPort(BanqueClientSOAP, BanqueClient.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BanqueClient
     */
    @WebEndpoint(name = "BanqueClientSOAP")
    public BanqueClient getBanqueClientSOAP(WebServiceFeature... features) {
        return super.getPort(BanqueClientSOAP, BanqueClient.class, features);
    }

}
