package fr.univ_lyon1.master_info.m2ti.tiw5.services.livraison.feedback;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.5.0
 * 2011-12-16T11:04:06.189+01:00
 * Generated source version: 2.5.0
 * 
 */
@WebService(targetNamespace = "http://master-info.univ-lyon1.fr/M2TI/TIW5/services/livraison/feedback", name = "LivraisonFeedback")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface LivraisonFeedback {

    @Oneway
    @WebMethod(operationName = "InformeLivraisonOp", action = "http://master-info.univ-lyon1.fr/M2TI/TIW5/services/livraison/feedback/InformeLivraisonOp")
    public void informeLivraisonOp(
        @WebParam(partName = "parameters", name = "livraisonEffectuee", targetNamespace = "http://master-info.univ-lyon1.fr/M2TI/TIW5/services/livraison/feedback")
        LivraisonEffectuee parameters
    );

    @Oneway
    @WebMethod(operationName = "InformePriseEnCompteOp")
    public void informePriseEnCompteOp(
        @WebParam(partName = "parameters", name = "InformePriseEnCompte", targetNamespace = "http://master-info.univ-lyon1.fr/M2TI/TIW5/services/livraison/feedback")
        InformePriseEnCompte parameters
    );
}
