package fr.univ_lyon1.master_info.m2ti.tiw5.services_owl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2012-01-24T15:04:18.940+01:00
 * Generated source version: 2.4.2
 * 
 */
@WebService(targetNamespace = "http://master-info.univ-lyon1.fr/M2TI/TIW5/services_owl", name = "OWLMapping")
@XmlSeeAlso({ObjectFactory.class})
public interface OWLMapping {

    @WebResult(name = "target", targetNamespace = "")
    @RequestWrapper(localName = "mapOWL", targetNamespace = "http://master-info.univ-lyon1.fr/M2TI/TIW5/services_owl", className = "fr.univ_lyon1.master_info.m2ti.tiw5.services_owl.MapOWL")
    @WebMethod
    @ResponseWrapper(localName = "mapOWLResponse", targetNamespace = "http://master-info.univ-lyon1.fr/M2TI/TIW5/services_owl", className = "fr.univ_lyon1.master_info.m2ti.tiw5.services_owl.MapOWLResponse")
    public java.lang.String mapOWL(
        @WebParam(name = "filepath1", targetNamespace = "")
        java.lang.String filepath1,
        @WebParam(name = "filepath2", targetNamespace = "")
        java.lang.String filepath2
    );
}
