package fr.univ_lyon1.master_info.m2ti.tiw5.services_cao.owl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2012-01-16T21:04:46.081+01:00
 * Generated source version: 2.4.2
 * 
 */
@WebServiceClient(name = "CAOOwl", 
                  wsdlLocation = "file:/C:/Users/Seb/eclipse-projects/svn/SIC/projet/client/src/main/resources/CAOOwlService.wsdl",
                  targetNamespace = "http://master-info.univ-lyon1.fr/M2TI/TIW5/services_cao/owl") 
public class CAOOwl_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://master-info.univ-lyon1.fr/M2TI/TIW5/services_cao/owl", "CAOOwl");
    public final static QName CAOOwlSOAP = new QName("http://master-info.univ-lyon1.fr/M2TI/TIW5/services_cao/owl", "CAOOwlSOAP");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/Seb/eclipse-projects/svn/SIC/projet/client/src/main/resources/CAOOwlService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CAOOwl_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/Seb/eclipse-projects/svn/SIC/projet/client/src/main/resources/CAOOwlService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CAOOwl_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CAOOwl_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CAOOwl_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns CAOOwl
     */
    @WebEndpoint(name = "CAOOwlSOAP")
    public CAOOwl getCAOOwlSOAP() {
        return super.getPort(CAOOwlSOAP, CAOOwl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CAOOwl
     */
    @WebEndpoint(name = "CAOOwlSOAP")
    public CAOOwl getCAOOwlSOAP(WebServiceFeature... features) {
        return super.getPort(CAOOwlSOAP, CAOOwl.class, features);
    }

}
