
package fr.univ_lyon1.master_info.m2ti.tiw5.services;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2011-10-12T22:26:01.149+02:00
 * Generated source version: 2.4.2
 * 
 */
public final class AlbumDataPortType_AlbumDataPort_Client {

    private static final QName SERVICE_NAME = new QName("http://master-info.univ-lyon1.fr/M2TI/TIW5/services", "AlbumDataService");

    private AlbumDataPortType_AlbumDataPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = AlbumDataService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        AlbumDataService ss = new AlbumDataService(wsdlURL, SERVICE_NAME);
        AlbumDataPortType port = ss.getAlbumDataPort();  
        
        {
        System.out.println("Invoking addAlbumDescription...");
        fr.univ_lyon1.master_info.m2ti.tiw5.services.Album _addAlbumDescription_arg0 = null;
        port.addAlbumDescription(_addAlbumDescription_arg0);


        }
        {
        System.out.println("Invoking getAlbumDescription...");
        long _getAlbumDescription_arg0 = 0;
        fr.univ_lyon1.master_info.m2ti.tiw5.services.Album _getAlbumDescription__return = port.getAlbumDescription(_getAlbumDescription_arg0);
        System.out.println("getAlbumDescription.result=" + _getAlbumDescription__return);


        }

        System.exit(0);
    }

}
