
package fr.univ_lyon1.master_info.m2ti.tiw5.services;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2012-01-09T23:00:27.112+01:00
 * Generated source version: 2.4.2
 * 
 */
public final class CAODataBase_CAODataBaseSOAP_Client {

    private static final QName SERVICE_NAME = new QName("http://master-info.univ-lyon1.fr/M2TI/TIW5/services", "CAODataBase");

    private CAODataBase_CAODataBaseSOAP_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = CAODataBase_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        CAODataBase_Service ss = new CAODataBase_Service(wsdlURL, SERVICE_NAME);
        CAODataBase port = ss.getCAODataBaseSOAP();  
        
        {
        System.out.println("Invoking getProduitList...");
        java.util.List<fr.univ_lyon1.master_info.m2ti.tiw5.services.PnumPnom> _getProduitList__return = port.getProduitList();
        System.out.println("getProduitList.result=" + _getProduitList__return);


        }
        {
        System.out.println("Invoking addProduit...");
        long _addProduit_pnum = 0;
        java.lang.String _addProduit_pnom = "";
        java.lang.Boolean _addProduit__return = port.addProduit(_addProduit_pnum, _addProduit_pnom);
        System.out.println("addProduit.result=" + _addProduit__return);


        }

        System.exit(0);
    }

}
