package fr.univ_lyon1.master_info.m2ti.tiw5.services;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2011-10-21T18:36:35.822+02:00
 * Generated source version: 2.4.2
 * 
 */
@WebServiceClient(name = "stock", 
                  wsdlLocation = "file:/C:/Users/Seb/eclipse-projects/svn/TIW5/tp2/projet/services-impl/src/main/resources/stock.wsdl",
                  targetNamespace = "http://master-info.univ-lyon1.fr/M2TI/TIW5/services") 
public class Stock_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://master-info.univ-lyon1.fr/M2TI/TIW5/services", "stock");
    public final static QName StockSOAP = new QName("http://master-info.univ-lyon1.fr/M2TI/TIW5/services", "stockSOAP");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/Seb/eclipse-projects/svn/TIW5/tp2/projet/services-impl/src/main/resources/stock.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(Stock_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/Seb/eclipse-projects/svn/TIW5/tp2/projet/services-impl/src/main/resources/stock.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public Stock_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public Stock_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Stock_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns Stock
     */
    @WebEndpoint(name = "stockSOAP")
    public Stock getStockSOAP() {
        return super.getPort(StockSOAP, Stock.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Stock
     */
    @WebEndpoint(name = "stockSOAP")
    public Stock getStockSOAP(WebServiceFeature... features) {
        return super.getPort(StockSOAP, Stock.class, features);
    }

}
