package sic.services.caodatabase;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2012-01-07T20:00:39.340+01:00
 * Generated source version: 2.4.2
 * 
 */
@WebService(targetNamespace = "caodatabase.services.sic", name = "CAODataBase")
@XmlSeeAlso({ObjectFactory.class})
public interface CAODataBase {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "addProduit", targetNamespace = "caodatabase.services.sic", className = "sic.services.caodatabase.AddProduit")
    @WebMethod
    @ResponseWrapper(localName = "addProduitResponse", targetNamespace = "caodatabase.services.sic", className = "sic.services.caodatabase.AddProduitResponse")
    public java.lang.Boolean addProduit(
        @WebParam(name = "pnum", targetNamespace = "")
        long pnum,
        @WebParam(name = "pnom", targetNamespace = "")
        java.lang.String pnom
    );
}
