package fr.univ_lyon1.master_info.m2ti.tiw5.services;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2011-10-20T19:04:54.090+02:00
 * Generated source version: 2.4.2
 * 
 */
@WebService(targetNamespace = "http://master-info.univ-lyon1.fr/M2TI/TIW5/services", name = "stock")
@XmlSeeAlso({ObjectFactory.class})
public interface Stock {

    @WebResult(name = "out", targetNamespace = "")
    @RequestWrapper(localName = "disponible", targetNamespace = "http://master-info.univ-lyon1.fr/M2TI/TIW5/services", className = "fr.univ_lyon1.master_info.m2ti.tiw5.services.Disponible")
    @WebMethod(action = "http://master-info.univ-lyon1.fr/M2TI/TIW5/services/NewOperation")
    @ResponseWrapper(localName = "disponibleResponse", targetNamespace = "http://master-info.univ-lyon1.fr/M2TI/TIW5/services", className = "fr.univ_lyon1.master_info.m2ti.tiw5.services.DisponibleResponse")
    public java.lang.String disponible(
        @WebParam(name = "in", targetNamespace = "")
        java.lang.String in
    );

    @WebResult(name = "out", targetNamespace = "")
    @RequestWrapper(localName = "commande", targetNamespace = "http://master-info.univ-lyon1.fr/M2TI/TIW5/services", className = "fr.univ_lyon1.master_info.m2ti.tiw5.services.Commande")
    @WebMethod
    @ResponseWrapper(localName = "commandeResponse", targetNamespace = "http://master-info.univ-lyon1.fr/M2TI/TIW5/services", className = "fr.univ_lyon1.master_info.m2ti.tiw5.services.CommandeResponse")
    public java.lang.String commande(
        @WebParam(name = "in", targetNamespace = "")
        java.lang.String in
    );

    @WebResult(name = "out", targetNamespace = "")
    @RequestWrapper(localName = "assureCapacite", targetNamespace = "http://master-info.univ-lyon1.fr/M2TI/TIW5/services", className = "fr.univ_lyon1.master_info.m2ti.tiw5.services.AssureCapacite")
    @WebMethod
    @ResponseWrapper(localName = "assureCapaciteResponse", targetNamespace = "http://master-info.univ-lyon1.fr/M2TI/TIW5/services", className = "fr.univ_lyon1.master_info.m2ti.tiw5.services.AssureCapaciteResponse")
    public java.lang.String assureCapacite(
        @WebParam(name = "in", targetNamespace = "")
        java.lang.String in
    );
}
